### PR TITLE
MINOR: backend: add new parameters

### PR DESCRIPTION
**Pull request by yuzhichang**
Add external-check to global, default, and backend options.

### CODE REVIEW

**Review by mjuraga — CHANGES_REQUESTED** [review]
I would change this as external-check-path-command is a confusing name and would just create three new parameters for backend and default:

```external_check``` - that is boolean and represents option external-check (when in defaults and backend)
```external_check_path``` 
```external_check_command```

Also be sure to add ```pattern: '^[^\s]+$'``` when using type string that is just one word.

**Comment by yuzhichang** [comment]
@mjuraga Updated per your comments.

**Review by mjuraga — CHANGES_REQUESTED** [review]
Please remove x-nullable: true, this means that "" is an viable option, and it is not in this case.

Also change parameter names to snake-case, so: external-check -> external_check etc. After that it is good for a merge.

**Comment by yuzhichang** [comment]
@mjuraga  Updated per your comments again.

**Pull request merged**
